version: "3.9"

services:
  fastapi-blog:
    build: .
    container_name: fastapi_blog
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./posts:/app/posts 