name: Deploy to DigitalOcean

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          script: |
            # Make sure repo exists
            if [ ! -d ~/fastapi_blog ]; then
              git clone https://github.com/thisisnihal/fast-blog.git ~/fastapi_blog
            fi
            cd ~/fastapi_blog
            git pull origin main
            docker compose down
            docker compose up -d --build
